import { Inter } from "next/font/google";
import "./globals.css";
import ThemeToggler from "@/components/ThemeToggler";
import Script from "next/script";
import ThemeProvider from "@/providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang='en'
            suppressHydrationWarning>
            <head>
                <Script
                    src='./script.js'
                    strategy='beforeInteractive'
                    defer
                />
            </head>
            <body className={inter.className}>
                <ThemeProvider>
                    {children}
                    <ThemeToggler />
                </ThemeProvider>
            </body>
        </html>
    );
}
